title: "Muntaser Munem"
remote_theme: "mmistakes/minimal-mistakes"

# Author Information
author:
  name: "Muntaser Munem"
  avatar: "/img/pic.jpeg"   # Ensure your image is in the /img folder
  bio: "Mechanical Engineer | Manufacturing Enthusiast | Researcher"

# Social Links (optional)
social:
  github: https://github.com/muntaser009
  linkedin: https://linkedin.com/in/yourprofile

# Site URL (replace this with your GitHub repository URL)
url: "https://muntaser009.github.io"

# Plugins (optional but recommended)
plugins:
  - jekyll-seo-tag          # For better SEO
  - jekyll-sitemap          # Automatically generates a sitemap
  - jekyll-feed             # RSS feed generator

# Minimal Mistakes Configuration
theme_settings:
  layout: single             # Single-column layout for a modern look
  header:
    overlay_image: "/img/cover_2.jpg"  # Optional: Add a header cover image
    show_avatar: true         # Display profile picture in the header
  show_excerpts: true         # Shows summary of posts on the index page
